### ISSUE TITLE
SHIFT + W-KEY conflicts with Node Wrangler

### ISSUE THREAD

**Issue by Cayden22** [3DSinghVFX/align_nodes#1]
SHIFT + W-KEY used by Align Nodes is also used by Node Wrangler. How can one change the shortcut in Align Node to avoid the conflict?

**Comment by 3DSinghVFX** [comment]
Hi. You can change the shortcuts from the *Blender Preferences > Keymap*,
For *Align Pie*
![Screenshot from 2021-01-22 11-09-18](https://user-images.githubusercontent.com/30294746/105451398-81f97a00-5ca2-11eb-8dbe-b2d54970b2d8.png)


For *Snap Pie*
![Screenshot from 2021-01-22 11-09-45](https://user-images.githubusercontent.com/30294746/105451418-8a51b500-5ca2-11eb-9dd1-931a9d484254.png)

**Comment by Cayden22** [comment]
Thank you for your quick response. I should have thought of that. I left Align Nodes unchanged and removed the shortcut from Node Wrangler to solve the conflict.

Ian

**Comment by 3DSinghVFX** [comment]
Okay. I'll close this. Feel free to reopen if needed.
