### ISSUE TITLE
Blender 2.93 Support

### ISSUE THREAD

**Issue by VeissieV** [3DSinghVFX/align_nodes#3]
Doesn't seem to work in 2.93. I have it installed but the pie menus don't come up when using the default shortcuts or custom shortcuts.

Looking forward to getting this working. It looks very helpful :)

Thanks

**Comment by 3DSinghVFX** [comment]
It seems to work on my side. Can you please try the fresh installation of the addon?

**Comment by VeissieV** [comment]
Seems to be working fine now in 3.1.2
Thanks

**Comment by 3DSinghVFX** [comment]
The issue is resolved, so I'm closing it.
